### PR TITLE
Add manual refresh button

### PR DESCRIPTION
**Pull request by betaveros**
Add a button that updates the sidebar so that you can interact with the
Mavo app and manually refresh the Mavo inspector's view of the data.

### CODE REVIEW

**Comment by betaveros** [comment]
(Maybe there is a Mavo hook or something that we can use to automatically refresh the inspector when needed, so we don't need this? But I'm not sure what it is.)

**Comment by LeaVerou** [comment]
Merged, thanks!

Not sure why `preventDefault` is needed though, what default action is it preventing? 

Also, perhaps we could use an emoji like 🔄 for the visible text, and "Refresh" in `title`, which would make it much smaller.

**Comment by LeaVerou** [comment]
> (Maybe there is a Mavo hook or something that we can use to automatically refresh the inspector when needed, so we don't need this? But I'm not sure what it is.)

Oh actually yeah. You could listen to the `mv-change` event!

**Comment by LeaVerou** [comment]
I just noticed a bug with this refresh button: I had evaluated an expression and was looking at its results. I hit the Refresh button, hoping that my expression would get re-evaluated. Instead, both the expression and its results disappeared!
Given the proximity of the Refresh button to the expression evaluation textfield, this is very unexpected behavior.

**Pull request merged**
